# This is a basic workflow to help you get started with Actions

name: Prime Binder

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, binder ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a set of commands using the runners shell
    - name: Prime binder with curl
      run: |
        curl 'https://mybinder.org/v2/gh/seandavi/sars2pack/binder'
        curl 'https://mybinder.org/v2/gh/seandavi/sars2pack/master'
